---
# vars file for osp.servers
osp_servers:
  frontend:
    name: frontend
    state: present
    nics: 
    - net-name: int_network
    int_network: int_network
    ext_network: ext_network
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: frontend
    userdata: |-
            #!/bin/bash
            ls -l /home/
            mkdir -p /home/cloud-user/.ssh/authorized_keys 
            curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
            cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys

    meta:
      - { group: frontends, deployment_name: QA}
  app1:
    name: app1
    state: present
    image: rhel-guest
    nics: 
    - net-name: int_network
    int_network: int_network
    ext_network: ext_network
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    userdata: |-
            #!/bin/bash
            ls -l /home/
            mkdir -p /home/cloud-user/.ssh/authorized_keys 
            curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
            cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
    meta:
      - { group: apps, deployment_name: QA}
  app2:
    name: app2
    state: present
    nics: 
    - net-name: int_network
    int_network: int_network
    ext_network: ext_network
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps

    userdata: |-
            #!/bin/bash
            ls -l /home/
            mkdir -p /home/cloud-user/.ssh/authorized_keys 
            curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
            cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
    meta:
      - { group: apps, deployment_name: QA}
  db:
    name: db
    state: present
    image: rhel-guest
    nics: 
    - net-name: int_network
    int_network: int_network
    ext_network: ext_network
    key_name: ansible_ssh
    flavor: m1.medium
    
    userdata: |-
            #!/bin/bash
            ls -l /home/
            mkdir -p /home/cloud-user/.ssh/authorized_keys 
            curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
            cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
    security_group: db
    meta:
      - { group: appdbs, deployment_name: QA}
